version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: saif
    #   MONGO_INITDB_ROOT_PASSWORD: gomydevops
    env_file:
      - ./env/mongo.env
    container_name: mongodb
  backend:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./env/server.env
    depends_on:
      - mongodb
    container_name: backend

  frontend:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
    depends_on:
      - backend
    stdin_open: true
    tty: true
    container_name: frontend

volumes:
  data:
  logs:
